# Global settings for all applications
global:
  repoURL:  https://gitlab.ba.innovatrics.net/application-platform/argocd-infra.git
  targetRevision: HEAD
  project: default
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

infrastructure:
  #useInfrastructureAppOfAppsFromInfraRepo: true

  argocd:
    enabled: true
    sources:
      - repoURL: https://argoproj.github.io/argo-helm
        chart: argo-cd
        targetRevision: "7.8.2"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/argocd/values.yaml
            - $app_repo/infrastructure/argocd/values.yaml

  linkerd-crds:
    enabled: true
    namespace: linkerd
    sources:
      - repoURL: https://helm.linkerd.io/stable
        chart: linkerd-crds
        targetRevision: "1.8.0"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/linkerd-crds/values.yaml

  linkerd-control-plane:
    enabled: true
    namespace: linkerd
    sources:
      - repoURL: https://helm.linkerd.io/stable
        chart: linkerd-control-plane
        targetRevision: "1.16.11"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/linkerd/values.yaml
            - $app_repo/infrastructure/linkerd/values.yaml

  sealed-secrets:
    enabled: true
    namespace: sealed-secrets
    sources:
      - repoURL: https://bitnami-labs.github.io/sealed-secrets/
        chart: sealed-secrets
        targetRevision: "2.17.1"

  external-dns:
    enabled: true
    namespace: external-dns
    sources:
      - repoURL: https://kubernetes-sigs.github.io/external-dns/
        chart: external-dns
        targetRevision: "1.15.2"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/external-dns/values.yaml
            - $app_repo/infrastructure/external-dns/values.yaml

  cert-manager:
    enabled: true
    namespace: cert-manager
    includeDirectoryFromInfraRepo: infrastructure/cert-manager/resources/
    sources:
      - repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: "1.17.1"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/cert-manager/values.yaml

  nginx:
    enabled: true
    namespace: nginx
    sources:
      - repoURL: https://kubernetes.github.io/ingress-nginx
        chart: ingress-nginx
        targetRevision: "4.12.0"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/nginx/values.yaml

  lgtm-distributed:
    enabled: true
    namespace: observability
    directoryFromInfraRepo:
      include: infrastructure/lgtm-distributed/resources/*
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-operator-crds
        targetRevision: "18.0.1"
      - repoURL: https://grafana.github.io/helm-charts
        chart: lgtm-distributed
        targetRevision: "2.1.0"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/lgtm-distributed/values.yaml
            - $app_repo/infrastructure/lgtm-distributed/values.yaml
      - repoURL: https://grafana.github.io/helm-charts
        chart: alloy
        targetRevision: 0.12.3
        helm:
          valueFiles:
            - $infra_repo/infrastructure/lgtm-distributed/values-alloy.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
