infrastructure:
  linkerd-bootstrap:
    enabled: true
    namespace: linkerd
    includeDirectoryFromInfraRepo: infrastructure/linkerd-bootstrap/resources/
    sources:
      - repoURL: https://helm.linkerd.io/stable
        chart: linkerd-crds
        targetRevision: "1.8.0"

  linkerd-control-plane:
    enabled: true
    namespace: linkerd
    sources:
      - repoURL: https://helm.linkerd.io/stable
        chart: linkerd-control-plane
        targetRevision: "1.16.11"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/linkerd-control-plane/values.yaml

  external-secrets:
    enabled: true
    namespace: external-secrets
    includeDirectoryFromInfraRepo: infrastructure/external-secrets/resources/
    sources:
      - repoURL: https://charts.external-secrets.io/
        chart: external-secrets
        targetRevision: "0.14.4"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/external-secrets/values.yaml

  external-dns:
    enabled: true
    namespace: external-dns
    sources:
      - repoURL: https://kubernetes-sigs.github.io/external-dns/
        chart: external-dns
        targetRevision: "1.15.2"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/external-dns/values.yaml
            - $app_repo/infrastructure/external-dns/values.yaml

  cert-manager:
    enabled: true
    namespace: cert-manager
    includeDirectoryFromInfraRepo: infrastructure/cert-manager/resources/
    sources:
      - repoURL: https://charts.jetstack.io
        chart: cert-manager
        targetRevision: "1.17.1"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/cert-manager/values.yaml
      - repoURL: https://charts.jetstack.io
        chart: trust-manager
        targetRevision: "0.16.0"

  lgtm-distributed:
    enabled: true
    namespace: observability
    includeDirectoryFromInfraRepo: infrastructure/lgtm-distributed/resources/
    sources:
      - repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-operator-crds
        targetRevision: "18.0.1"
      - repoURL: https://grafana.github.io/helm-charts
        chart: lgtm-distributed
        targetRevision: "2.1.0"
        helm:
          valueFiles:
            - $infra_repo/infrastructure/lgtm-distributed/values.yaml
            - $app_repo/infrastructure/lgtm-distributed/values.yaml
            - $app_repo/infrastructure/lgtm-distributed/dashboards.yaml
      - repoURL: https://grafana.github.io/helm-charts
        chart: alloy
        targetRevision: 0.12.3
        helm:
          valueFiles:
            - $infra_repo/infrastructure/lgtm-distributed/values-alloy.yaml
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
    # https://github.com/argoproj/argo-cd/issues/11143#issuecomment-2360788104
    ignoreDifferences:
      - group: "apps"
        kind: "StatefulSet"
        jqPathExpressions:
          - ".spec.volumeClaimTemplates[].apiVersion"
          - ".spec.volumeClaimTemplates[].kind"
      - group: "monitoring.coreos.com"
        kind: "ServiceMonitor"
        jqPathExpressions:
          - ".spec.endpoints[].relabelings"
