grafana:
  replicas: 2
  env:
    GF_UNIFIED_ALERTING_ENABLED: "true"
    GF_UNIFIED_ALERTING_HA_LISTEN_ADDRESS: "${POD_IP}:9094"
    GF_UNIFIED_ALERTING_HA_PEERS: "grafana-alerting.{{ .Release.Namespace }}.svc.cluster.local:9094"
    GF_UNIFIED_ALERTING_HA_ADVERTISE_ADDRESS: "${POD_IP}:9094"
    GF_UNIFIED_ALERTING_HA_PEER_TIMEOUT: "15s"
    GF_DATABASE_TYPE: "postgres"
    GF_DATABASE_USER: "postgres"
    GF_DATABASE_NAME: "grafana"
    # # TODO: change to RDS instance
    # GF_DATABASE_HOST: "postgres-ha-postgresql-ha-pgpool.postgres-ha.svc.cluster.local:5432"
    # # TODO: change to secret after AWS Secrets Manager is ready
    # GF_DATABASE_PASSWORD: "postgres"
  extraExposePorts:
    - name: http-grafana
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: grafana-alert
      port: 9094
      targetPort: 9094
      protocol: TCP
