apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: application-platform-devops@innovatrics.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53: {}
